title: SunehB Portfolio
description: My Portfolio
theme: just-the-docs

url: https://sunehb.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  "Work Experience": https://SunehB.github.io/workexperience

aux_links_new_tab: false

nav_enabled: true
