title: SunehB Portfolio
description: My Portfolio
theme: just-the-docs

url: https://sunehb.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  "assignment-0 github": https://github.com/SunehB/sunehb-assignment-0.git
  

aux_links_new_tab: false

nav_enabled: true
